### ISSUE TITLE
After update deoplete raises error

### ISSUE THREAD

**Issue by carlitux** [Shougo/neoinclude.vim#21]
```bash
error caught in async handler 'deoplete_on_event [{'dict__dictionary': '', 'input': '', 'max_abbr_width': 135, 'encoding': 'utf-8', 'delay': 150, 'filetype': 'javascript', 'camelcase': 0, 'sources': [], '
complete_str': '', 'custom': {'_': {}}, 'bufvars': {}, 'ignorecase': 0, 'max_menu_width': 135, 'bufnr': 2, 'start_complete': '\udc80\udcfdR_', 'vars': {'deoplete#max_menu_width': 40, 'deoplete#keyword_pat
terns': {}, 'deoplete#member#prefix_patterns': {}, 'deoplete#sources#ternjs#tern_bin': 'tern', 'deoplete#_context': {}, 'deoplete#enable_refresh_always': 0, 'deoplete#omni#input_patterns': {}, 'deoplete#a
uto_refresh_delay': 50, 'deoplete#omni_patterns': {}, 'deoplete#disable_auto_complete': 0, 'deoplete#_keyword_patterns': {'_': '[a-zA-Z_]\\k*'}, 'deoplete#_channel_id': 8, 'deoplete#omni#functions': {}, '
deoplete#auto_complete_start_length': 2, 'deoplete#delimiters': ['/', '.', '::', ':', '#'], 'deoplete#_omni_patterns': {'xhtml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'mkd': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'h
tml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'xml': ['<', '<[^>]*\\s[[:alnum:]-]*'], 'markdown': ['<', '<[^>]*\\s[[:alnum:]-]*']}, 'deoplete#max_abbr_width': 80, 'deoplete#sources': {}, 'deoplete#enable_camel_c
ase': 0, 'deoplete#enable_profile': 0, 'deoplete#enable_smart_case': 0, 'deoplete#ignore_sources': {}, 'deoplete#_rank': {}, 'deoplete#enable_ignore_case': 0, 'deoplete#enable_at_startup': 1, 'deoplete#ma
x_list': 100, 'deoplete#_neovim_python_version': ['0.1.11'], 'deoplete#auto_complete_delay': 150}, 'bufname': 'migrations/20161125154032-add-member-family-fields.js', 'cwd': '/Users/carlitux/Projects/dent
al-server', 'position': [0, 5, 1, 0], 'runtimepath': '/Users/carlitux/.config/nvim,/etc/xdg/nvim,/Users/carlitux/.local/share/nvim/site,/usr/local/share/nvim/site,/Users/carlitux/.cache/dein/repos/github.
com/Shougo/vimproc.vim,/Users/carlitux/.cache/dein/repos/github.com/othree/javascript-libraries-syntax.vim,/Users/carlitux/.cache/dein/repos/github.com/maksimr/vim-jsbeautify,/Users/carlitux/.cache/dein/r
epos/github.com/leshill/vim-json,/Users/carlitux/.cache/dein/repos/github.com/pangloss/vim-javascript,/Users/carlitux/.cache/dein/repos/github.com/moll/vim-node,/Users/carlitux/.cache/dein/repos/github.co
m/editorconfig/editorconfig-vim,/Users/carlitux/.cache/dein/repos/github.com/Shougo/deoplete.nvim,/Users/carlitux/.cache/dein/.cache/init.vim/.dein,/usr/share/nvim/site,/usr/local/Cellar/neovim/HEAD-42736
d6/share/nvim/runtime,/usr/share/nvim/site/after,/usr/local/share/nvim/site/after,/Users/carlitux/.local/share/nvim/site/after,/etc/xdg/nvim/after,/Users/carlitux/.config/nvim/after,/Users/carlitux/.confi
g/nvim/bundle/dein.vim/,/Users/carlitux/.cache/dein/.cache/init.vim/.dein/after,/Users/carlitux/.cache/dein/repos/github.com/pangloss/vim-javascript/after,/Users/carlitux/.cache/dein/repos/github.com/othr
ee/javascript-libraries-syntax.vim/after', 'next_input': '', 'filetypes': ['javascript'], 'smartcase': 0, 'same_filetypes': [], 'event': 'BufRead', 'keyword_patterns': '[a-zA-Z_][a-zA-Z@0-9_À-ÿ$]*', 'chan
gedtick': 10, 'rpc': 'deoplete_on_event', 'omni__omnifunc': 'javascriptcomplete#CompleteJS'}]'
Traceback (most recent call last):
  File "/Users/carlitux/.cache/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/__init__.py", line 62, in on_event
    self.__deoplete.on_event(context)
  File "/Users/carlitux/.cache/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/deoplete.py", line 380, in on_event
    source.on_event(context)
  File "/Users/carlitux/.cache/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/tag.py", line 34, in on_event
    self.__tagfiles[context['bufnr']] = self.__get_tagfiles(context)
  File "/Users/carlitux/.cache/dein/repos/github.com/Shougo/deoplete.nvim/rplugin/python3/deoplete/source/tag.py", line 58, in __get_tagfiles
    'exists', '*neoinclude#include#get_tag_files') else []
  File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 230, in call
    return self.request('nvim_call_function', name, args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/neovim/api/nvim.py", line 131, in request
    res = self._session.request(name, *args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/neovim/msgpack_rpc/session.py", line 98, in request
    raise self.error_wrapper(err)
neovim.api.nvim.NvimError: b'Vim(return):E121: Variable sin definir: command'
```

**Comment by zfogg** [comment]
+1 same for me. gonna rollback for now

**Comment by twidxuga** [comment]
+1 same here

**Comment by whisper404** [comment]
also makes neocomplete error.
[neocomplete] function <SNR>108_complete_delay[3]..<SNR>108_do_auto_complete[43]..neocomplete#complete#_get_results[23]..neocomplete#complete#_set_results_words[25]..46[3]..neocomplete#sources#tag#make_cache[10]..neoinclude#include#get_tag_files[3]..<SNR>122_check_buffer[59]..<SNR>122_initialize_include[20]..neoinclude#util#async_system, line 4
[neocomplete] Vim(return):E121: Undefined variable: command
[neocomplete] Source name is tag
[neocomplete] Error occurred in source's gather_candidates()!

Error detected while processing function neocomplete#sources#tag#make_cache[10]..neoinclude#include#get_tag_files[3]..<SNR>122_check_buffer[59]..<SNR>122_initialize_include[20]..neoinclude#util#async_system:
line    4:
E121: Undefined variable: command
E116: Invalid arguments for function job_start(command)
E15: Invalid expression: job_start(command)
Error detected while processing function neocomplete#sources#tag#make_cache:
line   10:
E734: Wrong variable type for +=
Error detected while processing function <SNR>122_check_buffer[59]..<SNR>122_initialize_include[20]..neoinclude#util#async_system:
line    4:
E121: Undefined variable: command
E116: Invalid arguments for function job_start(command)
E15: Invalid expression: job_start(command)

**Comment by akatrevorjay** [comment]
There are two PRs open for this, seems to just be a quick editing error, see there for fixes.

**Comment by wsdjeg** [comment]
https://github.com/Shougo/neoinclude.vim/blob/master/autoload/neoinclude/util.vim#L119-L131

here is where the error is!

**Comment by Coacher** [comment]
I can confirm the problem with latest neocomplete, neoinclude and vim-8.0.0104.
The error is the same as in whisper404's comment.

**Comment by Shougo** [comment]
Please update neoinclude.
